main:
  - name: What We Offer
    url: "#what-we-offer"
    weight: 10
  - name: Our Vision
    url: "#our-vision"
    weight: 20
  - name: Our Team
    url: "#our-team"
    weight: 30

main_footer:
  - name: Privacy Policy
    url: "/privacy-policy/"
    weight: 10
  - name: Terms of Service
    url: "/terms-of-service/"
    weight: 20
  - name: Cookies Settings
    url: "/cookies-settings/"
    weight: 30
